#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GATE_RUN="${GATE_RUN:-$ROOT/.scratch/phase4-runs/$(date -u +%Y%m%dT%H%M%SZ)}"
LEDGER="$GATE_RUN/evidence-ledger.md"
umask 077
mkdir -p "$GATE_RUN"
if [[ -e "$LEDGER" ]]; then
  printf 'Evidence ledger already exists: %s\n' "$LEDGER" >&2
  exit 1
fi
: > "$LEDGER"
printf 'run_id: %s\ncommit: %s\nstarted_at_utc: %s\n\n' \
  "$(basename "$GATE_RUN")" "$(cd "$ROOT" && git rev-parse HEAD 2>/dev/null || printf unknown)" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$LEDGER"
printf '| scenario | state | notes |\n|---:|---|---|\n' >> "$LEDGER"

record() {
  local scenario="$1" state="$2" notes="$3"
  notes=${notes//|/\\|}
  notes=${notes//$'\n'/ }
  printf '| %s | %s | %s |\n' "$scenario" "$state" "$notes" >> "$LEDGER"
}

ask_state() {
  local scenario="$1" description="$2" state notes
  while :; do
    printf '  Scenario %s: %s\n' "$scenario" "$description"
    printf '  State [PASS/BLOCKED/FAIL/NOT RUN]: '
    read -r state || true
    state=$(printf '%s' "$state" | tr '[:lower:]' '[:upper:]')
    case "$state" in PASS|BLOCKED|FAIL|NOT\ RUN) break;; *) warn "use PASS, BLOCKED, FAIL, or NOT RUN";; esac
  done
  while :; do
    printf '  Short redacted note: '
    read -r notes || true
    if [[ "$state" != "PASS" || -n "$notes" ]]; then
      break
    fi
    warn "PASS requires a short redacted evidence note"
  done
  [[ -n "$notes" ]] || notes="no note"
  record "$scenario" "$state" "$notes"
}

SCENARIOS=(
  "clean Secretary server"
  "MacBook and home-server Nodes connected"
  "multiple HarnessInstances per Node"
  "Project path mappings"
  "Web and Telegram Personal Conversation"
  "message accepted and acknowledged"
  "default policy selects fx"
  "explicit Claude Code on MacBook"
  "unknown model visible error without fx fallback"
  "Worker and Turn without Task in Client API"
  "user.md preference reaches next Secretary turn"
  "acknowledgement precedes completion"
  "started, deltas, tool call/result, finished activity"
  "queued Secretary message and parallel Workers"
  "activity matches HarnessInstance capabilities"
  "Approval request from harness"
  "Approval and needs_input answered by Client B"
  "multiple Attempts and exactly one Result"
  "direct Result without Secretary turn"
  "unseen Result in next Secretary context"
  "follow-up keeps Worker binding"
  "explicit Codex on home server"
  "server restart during active Attempt"
  "network loss and outbox replay"
  "repeated command does not duplicate process"
  "interrupted recovery or native session recovery"
  "message_worker resume or Follow-up"
  "idle Worker uses no active capacity"
  "offline Node does not migrate Worker"
  "internal subagent has no child Worker"
  "retry only after terminal retryable outcome"
  "replayed inbound/action/event/Result is idempotent"
  "revoked Client denied"
  "revoked Node denied Dispatch"
  "offline Worker remains visible"
  "Telegram Worker Topic aggregation"
  "automated release gate"
  "real fx, Claude Code, Codex and conditional OpenCode"
)

banner "Phase 4 manual acceptance"

stage "Run directory"
say "This wizard records evidence only. It never stores pairing tokens, cookies, bot tokens, or model prompts."
say "Use a fresh GATE_RUN directory. Keep notes short and redact private hostnames and paths."
step "Review the current commit and confirm the repository is clean before starting."
if [[ -n "$(cd "$ROOT" && git status --porcelain)" ]]; then
  warn "working tree is not clean; resolve this before treating the run as release evidence"
  record "preflight" "BLOCKED" "working tree is dirty"
else
  record "preflight" "PASS" "working tree clean at wizard start"
fi
pause "Press Enter after choosing the fresh run directory and operator"

stage "Server and Nodes"
say "On the clean server, follow section 1 of docs/phase4-release-gate.md."
step "Start the server, pair both Nodes with one-time tokens, and capture only redacted inventory metadata."
step "Restart the server once and confirm the same Worker binding remains."
pause "Press Enter after the server and both Nodes have been checked"

stage "Harness authentication"
say "On each required Node, run sex doctor and authenticate fx, Claude Code, and Codex separately."
step "Do not copy credentials into this shell or into the ledger."
step "If a required harness is unavailable, record BLOCKED instead of substituting fx."
pause "Press Enter after harness status has been checked"

stage "Deterministic gate"
say "The deterministic gate is independent evidence and must be recorded separately."
if (cd "$ROOT" && "$ROOT/scripts/phase4-release-gate.sh") >"$GATE_RUN/deterministic-gate.log" 2>&1; then
  record "37" "PASS" "phase4-release-gate.sh log: deterministic-gate.log"
  note "Deterministic gate passed."
else
  record "37" "FAIL" "phase4-release-gate.sh log: deterministic-gate.log"
  warn "deterministic gate failed; do not mark the release accepted"
fi

stage "Scenario 24 matrix"
say "Run the manual scenarios from section 24 against this same GATE_RUN."
say "Use PASS only for reproducible evidence from the real harness."
for index in "${!SCENARIOS[@]}"; do
  scenario=$((index + 1))
  [[ "$scenario" == 37 ]] && continue
  ask_state "$scenario" "${SCENARIOS[$index]}"
done

stage "Security evidence"
say "Run the redaction, Client revoke, Node revoke, no-silent-fallback, and offline checks."
step "Use a synthetic sentinel, never a real secret, and record only the redacted surfaces."
step "Update the corresponding matrix rows above if a scenario changed state."
pause "Press Enter after security and revoke checks"

stage "Review and handoff"
say "Review the ledger for raw credentials, cookies, native session IDs, Task fields, or raw prompts."
matrix_ok=1
for scenario in $(seq 1 38); do
  state=$(awk -F'|' -v wanted="$scenario" '$2 ~ /^[[:space:]]*[0-9]+[[:space:]]*$/ && ($2 + 0) == wanted { value=$3 } END { gsub(/^[[:space:]]+|[[:space:]]+$/, "", value); print value }' "$LEDGER")
  if [[ "$state" != "PASS" ]]; then
    matrix_ok=0
    warn "scenario $scenario is $state, not PASS"
  fi
done
if (( matrix_ok )); then
  record "decision" "PASS" "all required matrix rows are PASS"
else
  record "decision" "BLOCKED" "one or more required matrix rows are not PASS"
  warn "acceptance is not complete; Ticket 15 must remain pending"
fi
if grep -Eiq 'token|cookie|credential|password|secret|api[_ -]?key' "$LEDGER"; then
  warn "ledger contains a sensitive-looking word; inspect it manually before sharing"
fi
printf '  Evidence ledger: %s\n' "$LEDGER"
printf '  Deterministic log: %s\n' "$GATE_RUN/deterministic-gate.log"
pause "Press Enter after the ledger review"
warn "Review the ledger manually. This wizard never changes Ticket 15 status to resolved."

finish
